name: Simple CI/CD Pipeline  # [!note] Defines the workflow name that appears in GitHub Actions tab
on:
  push:
    branches: [ main ]  # [!note] Triggered on `push` on `main` branch
  pull_request:
    branches: [ main ]  # [!note] Triggered on `pool request` on `main` branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # [!note] Specifies the runner environment (Ubuntu virtual machine)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # [!note] Uses `pre-built action` to `download repository code` to runner

      - name: Setup Java 21
        uses: actions/setup-java@v4  # [!note] Uses `pre-built action` to `install and configure Java`
        with:
          java-version: '21'  # [!note] Specifies Java version 21 to install
          distribution: 'temurin'  # [!note] Specifies Eclipse Temurin as the Java distribution

      - name: Run Tests
        run: ./gradlew test  # [!note] Executes Gradle test command `to run unit/integration tests`

      - name: Build Application
        run: ./gradlew bootJar  # [!note] Executes Gradle command to `create Spring Boot JAR file`

      - name: Create Release
        if: github.ref == 'refs/heads/main'  # [!note] `Conditional execution` - only runs on main branch pushes (not PRs)
        run: |  # [!note] Multi-line shell script block to `deploy project`
          VERSION="1.0.${{ github.run_number }}"
          echo "Built version: $VERSION" 
          echo "Ready for deployment!"